// Generated by CoffeeScript 1.7.1
(function() {
  var module, _ref,
    __slice = [].slice,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  if (window.Sizzle == null) {
    window.Sizzle = (_ref = window.$) != null ? _ref : null;
  }

  module = angular.module("angular-clazz", []);

  module.provider("Clazz", function() {
    var OO, err, _DB, _ref1;
    try {
      _DB = (_ref1 = angular.injector(['pouchdb'])) != null ? typeof _ref1.get === "function" ? _ref1.get('pouchdb') : void 0 : void 0;
    } catch (_error) {
      err = _error;
      console.info("Angular-PouchDB not available - you can't use local persistance, but volatile version is available");
    }
    OO = {};
    OO.Injectable = (function() {
      function Injectable() {}

      Injectable.inject = function() {
        var args, injectee, _i, _len, _ref2, _ref3;
        args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        _ref3 = __slice.call((_ref2 = this.$inject) != null ? _ref2 : []).concat(["$scope"]);
        for (_i = 0, _len = _ref3.length; _i < _len; _i++) {
          injectee = _ref3[_i];
          if (args.indexOf(injectee) === -1) {
            args.push(injectee);
          }
        }
        this.$inject = args;
        return this;
      };

      return Injectable;

    })();
    OO.Ctrl = (function(_super) {
      __extends(Ctrl, _super);

      Ctrl.register = function(app, name) {
        var _ref2;
        if (name == null) {
          name = this.name || ((_ref2 = this.toString().match(/function\s*(.*?)\(/)) != null ? _ref2[1] : void 0);
        }
        if (typeof app === "string") {
          angular.module(app).controller(name, this);
        } else {
          app.controller(name, this);
        }
        return this;
      };

      Ctrl.mixin = function() {
        var Mixed, method, mixin, mixins, name, _fn, _i, _len, _ref2;
        mixins = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        Mixed = (function(_super1) {
          __extends(Mixed, _super1);

          function Mixed() {
            return Mixed.__super__.constructor.apply(this, arguments);
          }

          return Mixed;

        })(this);
        for (_i = 0, _len = mixins.length; _i < _len; _i++) {
          mixin = mixins[_i];
          _ref2 = mixin.prototype;
          _fn = function() {
            var m, n, _m;
            m = method;
            _m = Mixed.prototype[name];
            n = name;
            if (name === "initialize" && (Mixed.prototype.initialize != null)) {
              return Mixed.prototype.initialize = function() {
                m.call(this);
                return _m.call(this);
              };
            } else if (name !== "constructor" && (Mixed.prototype[name] == null)) {
              return Mixed.prototype[name] = m;
            }
          };
          for (name in _ref2) {
            method = _ref2[name];
            _fn();
          }
          for (name in mixin) {
            if (!__hasProp.call(mixin, name)) continue;
            method = mixin[name];
            if (angular.isFunction(method)) {
              Mixed[name] = method;
            }
          }
          Mixed.inject.apply(Mixed, mixin.$inject);
        }
        return Mixed;
      };

      Ctrl["implements"] = function() {
        var Interface, Interfaced, interfaces, _fn, _i, _len;
        interfaces = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        Interfaced = (function(_super1) {
          __extends(Interfaced, _super1);

          function Interfaced() {
            return Interfaced.__super__.constructor.apply(this, arguments);
          }

          return Interfaced;

        })(this);
        _fn = function(Interface) {
          return Interfaced.prototype[Interface] = function() {
            throw {
              msg: "Looks like the interface _" + Interface + "_ hasn't been implemented! This will lead to unpredictable behaviour!"
            };
          };
        };
        for (_i = 0, _len = interfaces.length; _i < _len; _i++) {
          Interface = interfaces[_i];
          _fn(Interface);
        }
        return Interfaced;
      };

      function Ctrl() {
        var args, fn, index, key, _i, _len, _ref2, _ref3;
        args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        _ref2 = this.constructor.$inject;
        for (index = _i = 0, _len = _ref2.length; _i < _len; index = ++_i) {
          key = _ref2[index];
          this[key] = args[index];
        }
        _ref3 = this.constructor.prototype;
        for (key in _ref3) {
          fn = _ref3[key];
          if (typeof fn === "function" && ["constructor", "initialize"].indexOf(key) === -1 && key[0] !== "_") {
            (function(_this) {
              return (function(key, fn) {
                var el, i, t, _j, _len1, _ref4, _ref5, _ref6, _ref7, _results;
                if (key.match("::")) {
                  console.log(key);
                  t = key.split("::");
                  _ref7 = t[0] && Sizzle(t[0], (_ref4 = (_ref5 = _this.element) != null ? _ref5.context : void 0) != null ? _ref4 : document.body) || [(_ref6 = _this.$element) != null ? _ref6.context : void 0];
                  _results = [];
                  for (i = _j = 0, _len1 = _ref7.length; _j < _len1; i = ++_j) {
                    el = _ref7[i];
                    _results.push((function(el, i) {
                      var listenerO;
                      listenerO = [t[1]];
                      if (t[2] != null) {
                        listenerO.push(t[2]);
                      }
                      listenerO.push(function() {
                        var args, ev, j, _k, _len2, _ref8;
                        args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
                        console.log(key);
                        if (t[2] != null) {
                          ev = args[0];
                          _ref8 = $(ev.currentTarget).parent().children().get();
                          for (j = _k = 0, _len2 = _ref8.length; _k < _len2; j = ++_k) {
                            el = _ref8[j];
                            if (el === ev.currentTarget) {
                              i = j;
                            }
                          }
                        }
                        _this.$scope.n = i;
                        fn.apply(_this, args);
                        if (!_this.$scope.$$phase) {
                          return _this.$scope.$digest();
                        }
                      });
                      return angular.element(el).on.apply(angular.element(el), listenerO);
                    })(el, i));
                  }
                  return _results;
                } else {
                  return _this.$scope[key] = function() {
                    var args;
                    args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
                    fn.apply(_this, args);
                    return _this;
                  };
                }
              });
            })(this)(key, fn);
          }
        }
        if (typeof this.initialize === "function") {
          this.initialize();
        }
      }

      return Ctrl;

    })(OO.Injectable);
    OO.Service = (function(_super) {
      __extends(Service, _super);

      Service.register = function(app, name) {
        var _ref2;
        if (name == null) {
          name = this.name || ((_ref2 = this.toString().match(/function\s*(.*?)\(/)) != null ? _ref2[1] : void 0);
        }
        if (typeof app === "string") {
          angular.module(app).service(name, this);
        } else {
          app.service(name, this);
        }
        return this;
      };

      function Service() {
        var args, index, key, _i, _len, _ref2;
        args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        _ref2 = this.constructor.$inject;
        for (index = _i = 0, _len = _ref2.length; _i < _len; index = ++_i) {
          key = _ref2[index];
          this[key] = args[index];
        }
        if (typeof this.initialize === "function") {
          this.initialize();
        }
      }

      return Service;

    })(OO.Injectable);
    OO.DataService = (function(_super) {
      __extends(DataService, _super);

      function DataService() {
        return DataService.__super__.constructor.apply(this, arguments);
      }

      DataService.inject("$resource", "$interval");

      DataService.prototype._db = function(api, name, volatile, oneshot) {
        var _base;
        this.volatile = volatile != null ? volatile : false;
        this.oneshot = oneshot != null ? oneshot : false;
        if (this.db == null) {
          this.db = {};
        }
        if (this._q == null) {
          this._q = {};
        }
        if (this._q[name] != null) {
          return false;
        }
        if ((_base = this._q)[name] == null) {
          _base[name] = this.$q.defer();
        }
        this.db[name] = {
          busy: false,
          handle: api != null ? this.$resource(api) : null,
          raw: [],
          store: this.volatile && [] || _DB.create(name)
        };
        this._api(name);
        return this.oneshot || this.$interval(this._api.bind(this, name), 7000);
      };

      DataService.prototype._api = function(name) {
        if (this.db[name].busy === true) {
          return;
        }
        this.db[name].busy = true;
        return this.db[name].handle.get().$promise.then((function(_this) {
          return function(data) {
            var _ref2;
            _this._store(name, (_ref2 = data[name]) != null ? _ref2 : data);
            _this.db[name].busy = false;
            if (_this.volatile) {
              if (_this.oneshot === true) {
                _this._q[name].resolve();
                return _this._q[name] = null;
              } else {
                return _this._q[name].notify(true);
              }
            }
          };
        })(this))["catch"]((function(_this) {
          return function(err) {
            if (_this.oneshot === true) {
              _this._q[name].reject();
              return _this._q[name] = null;
            } else {
              return _this._q[name].notify(false);
            }
          };
        })(this));
      };

      DataService.prototype._store = function(name, data) {
        var o, _i, _j, _k, _len, _len1, _len2, _ref2, _ref3, _ref4, _results, _results1;
        data = (_ref2 = (_ref3 = data.contents) != null ? _ref3 : data.content) != null ? _ref2 : data;
        if (!this.volatile) {
          _results = [];
          for (_i = 0, _len = data.length; _i < _len; _i++) {
            o = data[_i];
            _results.push((function(_this) {
              return function(o) {
                return _this.db[name].store.query(function(doc, emit) {
                  if (doc.id === o.id) {
                    return emit(doc);
                  }
                }).then(function(doc) {
                  console.info('#Data for id _#{o.id}_ will be updated now');
                  if (doc.error !== "not_found" && doc.total_rows === 1) {
                    o._id = doc.rows[0].key._id;
                    return o._rev = doc.rows[0].key._rev;
                  }
                })["catch"](function(err) {
                  console.warn("db error: couldn't query for " + o.id);
                  throw err.toString();
                })["finally"](function() {
                  var args;
                  args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
                  return _this.db[name].store.put(o, o.id, o._rev).then(function(response) {
                    if (_this.oneshot === true) {
                      _this._q[name].resolve();
                      return _this._q[name] = null;
                    } else {
                      return _this._q[name].notify(true);
                    }
                  })["catch"](function(err) {
                    console.warn("db error: couldn't put " + (o.toString()));
                    if (_this.oneshot === true) {
                      _this._q[name].reject();
                      return _this._q[name] = null;
                    } else {
                      return _this._q[name].notify(false);
                    }
                  });
                });
              };
            })(this)(o));
          }
          return _results;
        } else {
          _ref4 = this.db[name].store;
          for (_j = 0, _len1 = _ref4.length; _j < _len1; _j++) {
            o = _ref4[_j];
            o.deleted = true;
          }
          _results1 = [];
          for (_k = 0, _len2 = data.length; _k < _len2; _k++) {
            o = data[_k];
            _results1.push((function(_this) {
              return function(o) {
                var i, k, v;
                if ((i = _this.db[name].store.findIndex(function(el) {
                  return el.id === o.id;
                })) !== -1) {
                  for (k in o) {
                    if (!__hasProp.call(o, k)) continue;
                    v = o[k];
                    _this.db[name].store[i][k] = o[k];
                  }
                  return _this.db[name].store[i].deleted = false;
                } else {
                  _this.db[name].store.push(o);
                  return _this.db[name].store[_this.db[name].store.length - 1].deleted = false;
                }
              };
            })(this)(o));
          }
          return _results1;
        }
      };

      return DataService;

    })(OO.Service);
    OO.Widget = (function(_super) {
      __extends(Widget, _super);

      function Widget() {
        return Widget.__super__.constructor.apply(this, arguments);
      }

      Widget.inject("$element");

      return Widget;

    })(OO.Ctrl);
    this.$get = function() {
      return OO;
    };
  });

}).call(this);
